module.exports = {
    type: 'postgres',
    host: process.env.NODE_ENV === 'test' ? process.env.TEST_DB_HOST : process.env.DB_HOST,
    port: process.env.NODE_ENV === 'test' ? process.env.TEST_DB_PORT : process.env.DB_PORT,
    username: process.env.NODE_ENV === 'test' ? process.env.TEST_DB_USERNAME : process.env.DB_USERNAME,
    password: process.env.NODE_ENV === 'test' ? process.env.TEST_DB_PASSWORD : process.env.DB_PASSWORD,
    database: process.env.NODE_ENV === 'test' ? process.env.TEST_DB_NAME : process.env.DB_NAME,
    synchronize: true,
    logging: false,
    dropSchema: process.env.NODE_ENV === 'test' ? true : false,
    entities: [__dirname + '/packages/models/entities/**/*.ts'],
    migrations: [__dirname + '/packages/db/migration/**/*.ts'],
    subscribers: [__dirname + '/packages/db/subscriber/**/*.ts'],
    seeds: [__dirname + '/packages/db/seeds/**/*{.ts,.js}'],
    factories: [__dirname + '/packages/db/factories/**/*{.ts,.js}'],
    cli: {
        entitiesDir: __dirname + '/packages/models/entities',
        migrationsDir: __dirname + '/migration',
        subscribersDir: __dirname + '/subscriber',
    },
};
