export const tableKeys = {
  users: 'users',
  deals: 'deals',
  earnings: 'earnings',
  orphaned_aliases: 'orphaned_aliases',
  payments: 'payments',
  user_payment_requests: 'user_payment_requests',
  user_payments: 'user_payments',
  colors: 'colors',
  news: 'news',
  promotions: 'promotions',
  public_rooms: 'public_rooms',
  translations: 'translations',
  crawlers: 'crawlers',
  data: 'data',
  rooms: 'rooms',
  admins: 'admins',
  currencies: 'currencies',
  languages: 'languages',
  referral_requests: 'referral_requests',
  logs: 'logs',
  products: 'products',
  categories: 'categories',
  snippets: 'snippets',
};
